version: '3.8'
services:
  openauth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openauth
    restart: always
    ports:
      - "8085:8085"
      - "8086:8086"
    environment:
      EXAMPLE_ENV: value
